# OpenDartReader 사용하기
https://github.com/financedata/opendartreader

![](https://camo.githubusercontent.com/2b313718426b1e464591764c3e54c6482282f558f5a1efb76bab8c8c9619ad0f/68747470733a2f2f692e696d6775722e636f6d2f464d734c3069642e706e67)


- 설치
    - **pip install opendartreader** 
- 사전에 필요한 것
    - DART_API_KEY

# import & 환경변수

In [1]:
import OpenDartReader

In [2]:
import os
from dotenv import load_dotenv
load_dotenv()

DART_API_KEY = os.getenv('DART_API_KEY')
print(f"{DART_API_KEY[:10]}...")

bb053e711b...

In [3]:
dart = OpenDartReader(DART_API_KEY)
dart

In [4]:
import pandas as pd
pd.set_option('display.max_columns', None)

# find_corp_code()
특정 기업명이나 종목코드에 해당하는 DART 고유번호(고유식별자)를 조회하는 함수

```python
dart.find_corp_code(기업명_또는_종목코드) -> str
```

In [5]:
corp_code = dart.find_corp_code('005930')
corp_code

'00126380'

## 🔵함수 정의

In [8]:
def get_corp_code(corp_name):
    return dart.find_corp_code(corp_name)

In [9]:
get_corp_code('삼성전자')

'00126380'

In [10]:
get_corp_code('005930')

'00126380'

# company()
특정 기업의 고유번호(또는 종목코드)로 해당 기업의 개황 정보(기업명, 대표자, 설립일, 주소 등 기본 정보)를 조회하는 함수

```python
dart.company (고유번호_또는_종목코드) -> dict
```

In [11]:
dart.company(corp_code)

{'status': '000',
 'message': '정상',
 'corp_code': '00126380',
 'corp_name': '삼성전자(주)',
 'corp_name_eng': 'SAMSUNG ELECTRONICS CO,.LTD',
 'stock_name': '삼성전자',
 'stock_code': '005930',
 'ceo_nm': '전영현, 노태문',
 'corp_cls': 'Y',
 'jurir_no': '1301110006246',
 'bizr_no': '1248100998',
 'adres': '경기도 수원시 영통구  삼성로 129 (매탄동)',
 'hm_url': 'www.samsung.com/sec',
 'ir_url': '',
 'phn_no': '02-2255-0114',
 'fax_no': '031-200-7538',
 'induty_code': '264',
 'est_dt': '19690113',
 'acc_mt': '12'}

In [12]:
dart.company('005930')

{'status': '000',
 'message': '정상',
 'corp_code': '00126380',
 'corp_name': '삼성전자(주)',
 'corp_name_eng': 'SAMSUNG ELECTRONICS CO,.LTD',
 'stock_name': '삼성전자',
 'stock_code': '005930',
 'ceo_nm': '전영현, 노태문',
 'corp_cls': 'Y',
 'jurir_no': '1301110006246',
 'bizr_no': '1248100998',
 'adres': '경기도 수원시 영통구  삼성로 129 (매탄동)',
 'hm_url': 'www.samsung.com/sec',
 'ir_url': '',
 'phn_no': '02-2255-0114',
 'fax_no': '031-200-7538',
 'induty_code': '264',
 'est_dt': '19690113',
 'acc_mt': '12'}

## 🔵함수정의

In [15]:
def get_company_overview(corp_code):
    return dart.company(corp_code)

In [16]:
get_company_overview('005930')

{'status': '000',
 'message': '정상',
 'corp_code': '00126380',
 'corp_name': '삼성전자(주)',
 'corp_name_eng': 'SAMSUNG ELECTRONICS CO,.LTD',
 'stock_name': '삼성전자',
 'stock_code': '005930',
 'ceo_nm': '전영현, 노태문',
 'corp_cls': 'Y',
 'jurir_no': '1301110006246',
 'bizr_no': '1248100998',
 'adres': '경기도 수원시 영통구  삼성로 129 (매탄동)',
 'hm_url': 'www.samsung.com/sec',
 'ir_url': '',
 'phn_no': '02-2255-0114',
 'fax_no': '031-200-7538',
 'induty_code': '264',
 'est_dt': '19690113',
 'acc_mt': '12'}

# finstate()
특정 기업의 특정 연도(및 분기)에 대한 재무제표(재무상태표, 손익계산서 등)를 조회하는 함수

```python
dart.finstate(기업명_또는_종목코드, 연도, reprt_code=보고서코드) -> DataFrame
```

In [17]:
# 파라미터에는 기업명이나 종목코드(예: '삼성전자', '005930), 
# 조회할 연도(예: 2021), 
# 보고서 코드(예: '11011(사업보고서)', '11013 (1분기보고서)', '110143분기보고서)', '11012(반기보고서))를 
# 전달합니다.

In [18]:
# 삼성전자의 2021년 연간 재무재표
df = dart.finstate('삼성전자', 2021)
df

,rcept_no,reprt_code,bsns_year,corp_code,stock_code,fs_div,fs_nm,sj_div,sj_nm,account_nm,thstrm_nm,thstrm_dt,thstrm_amount,frmtrm_nm,frmtrm_dt,frmtrm_amount,bfefrmtrm_nm,bfefrmtrm_dt,bfefrmtrm_amount,ord,currency
0,20220308000798,11011,2021,00126380,005930,CFS,연결재무제표,BS,재무상태표,유동자산,제 53 기,2021.12.31 현재,"218,163,185,000,000",제 52 기,2020.12.31 현재,"198,215,579,000,000",제 51 기,2019.12.31 현재,"181,385,260,000,000",1,KRW
1,20220308000798,11011,2021,00126380,005930,CFS,연결재무제표,BS,재무상태표,비유동자산,제 53 기,2021.12.31 현재,"208,457,973,000,000",제 52 기,2020.12.31 현재,"180,020,139,000,000",제 51 기,2019.12.31 현재,"171,179,237,000,000",3,KRW
2,20220308000798,11011,2021,00126380,005930,CFS,연결재무제표,BS,재무상태표,자산총계,제 53 기,2021.12.31 현재,"426,621,158,000,000",제 52 기,2020.12.31 현재,"378,235,718,000,000",제 51 기,2019.12.31 현재,"352,564,497,000,000",5,KRW
3,20220308000798,11011,2021,00126380,005930,CFS,연결재무제표,BS,재무상태표,유동부채,제 53 기,2021.12.31 현재,"88,117,133,000,000",제 52 기,2020.12.31 현재,"75,604,351,000,000",제 51 기,2019.12.31 현재,"63,782,764,000,000",7,KRW
4,20220308000798,11011,2021,00126380,005930,CFS,연결재무제표,BS,재무상태표,비유동부채,제 53 기,2021.12.31 현재,"33,604,094,000,000",제 52 기,2020.12.31 현재,"26,683,351,000,000",제 51 기,2019.12.31 현재,"25,901,312,000,000",9,KRW
5,20220308000798,11011,2021,00126380,005930,CFS,연결재무제표,BS,재무상태표,부채총계,제 53 기,2021.12.31 현재,"121,721,227,000,000",제 52 기,2020.12.31 현재,"102,287,702,000,000",제 51 기,2019.12.31 현재,"89,684,076,000,000",11,KRW
6,20220308000798,11011,2021,00126380,005930,CFS,연결재무제표,BS,재무상태표,자본금,제 53 기,2021.12.31 현재,"897,514,000,000",제 52 기,2020.12.31 현재,"897,514,000,000",제 51 기,2019.12.31 현재,"897,514,000,000",13,KRW
7,20220308000798,11011,2021,00126380,005930,CFS,연결재무제표,BS,재무상태표,이익잉여금,제 53 기,2021.12.31 현재,"293,064,763,000,000",제 52 기,2020.12.31 현재,"271,068,211,000,000",제 51 기,2019.12.31 현재,"254,582,894,000,000",17,KRW
8,20220308000798,11011,2021,00126380,005930,CFS,연결재무제표,BS,재무상태표,자본총계,제 53 기,2021.12.31 현재,"304,899,931,000,000",제 52 기,2020.12.31 현재,"275,948,016,000,000",제 51 기,2019.12.31 현재,"262,880,421,000,000",21,KRW
9,20220308000798,11011,2021,00126380,005930,CFS,연결재무제표,IS,손익계산서,매출액,제 53 기,2021.01.01 ~ 2021.12.31,"279,604,799,000,000",제 52 기,2020.01.01 ~ 2020.12.31,"236,806,988,000,000",제 51 기,2019.01.01 ~ 2019.12.31,"230,400,881,000,000",23,KRW
10,20220308000798,11011,2021,00126380,005930,CFS,연결재무제표,IS,손익계산서,영업이익,제 53 기,2021.01.01 ~ 2021.12.31,"51,633,856,000,000",제 52 기,2020.01.01 ~ 2020.12.31,"35,993,876,000,000",제 51 기,2019.01.01 ~ 2019.12.31,"27,768,509,000,000",25,KRW
11,20220308000798,11011,2021,00126380,005930,CFS,연결재무제표,IS,손익계산서,법인세차감전 순이익,제 53 기,2021.01.01 ~ 2021.12.31,"53,351,827,000,000",제 52 기,2020.01.01 ~ 2020.12.31,"36,345,117,000,000",제 51 기,2019.01.01 ~ 2019.12.31,"30,432,189,000,000",27,KRW
12,20220308000798,11011,2021,00126380,005930,CFS,연결재무제표,IS,손익계산서,당기순이익(손실),제 53 기,2021.01.01 ~ 2021.12.31,"39,907,450,000,000",제 52 기,2020.01.01 ~ 2020.12.31,"26,407,832,000,000",제 51 기,2019.01.01 ~ 2019.12.31,"21,738,865,000,000",29,KRW
13,20220308000798,11011,2021,00126380,005930,CFS,연결재무제표,IS,손익계산서,당기순이익(손실),제 53 기,2021.01.01 ~ 2021.12.31,"39,907,450,000,000",제 52 기,2020.01.01 ~ 2020.12.31,"26,407,832,000,000",제 51 기,2019.01.01 ~ 2019.12.31,"21,738,865,000,000",61,KRW
14,20220308000798,11011,2021,00126380,005930,OFS,재무제표,BS,재무상태표,유동자산,제 53 기,2021.12.31 현재,"73,553,416,000,000",제 52 기,2020.12.31 현재,"73,798,549,000,000",제 51 기,2019.12.31 현재,"72,659,080,000,000",2,KRW
15,20220308000798,11011,2021,00126380,005930,OFS,재무제표,BS,재무상태표,비유동자산,제 53 기,2021.12.31 현재,"177,558,768,000,000",제 52 기,2020.12.31 현재,"155,865,878,000,000",제 51 기,2019.12.31 현재,"143,521,840,000,000",4,KRW
16,20220308000798,11011,2021,00126380,005930,OFS,재무제표,BS,재무상태표,자산총계,제 53 기,2021.12.31 현재,"251,112,184,000,000",제 52 기,2020.12.31 현재,"229,664,427,000,000",제 51 기,2019.12.31 현재,"216,180,920,000,000",6,KRW
17,20220308000798,11011,2021,00126380,005930,OFS,재무제표,BS,재무상태표,유동부채,제 53 기,2021.12.31 현재,"53,067,303,000,000",제 52 기,2020.12.31 현재,"44,412,904,000,000",제 51 기,2019.12.31 현재,"36,237,164,000,000",8,KRW
18,20220308000798,11011,2021,00126380,005930,OFS,재무제표,BS,재무상태표,비유동부채,제 53 기,2021.12.31 현재,"4,851,149,000,000",제 52 기,2020.12.31 현재,"1,934,799,000,000",제 51 기,2019.12.31 현재,"2,073,509,000,000",10,KRW
19,20220308000798,11011,2021,00126380,005930,OFS,재무제표,BS,재무상태표,부채총계,제 53 기,2021.12.31 현재,"57,918,452,000,000",제 52 기,2020.12.31 현재,"46,347,703,000,000",제 51 기,2019.12.31 현재,"38,310,673,000,000",12,KRW
20,20220308000798,11011,2021,00126380,005930,OFS,재무제표,BS,재무상태표,자본금,제 53 기,2021.12.31 현재,"897,514,000,000",제 52 기,2020.12.31 현재,"897,514,000,000",제 51 기,2019.12.31 현재,"897,514,000,000",15,KRW
21,20220308000798,11011,2021,00126380,005930,OFS,재무제표,BS,재무상태표,이익잉여금,제 53 기,2021.12.31 현재,"188,774,335,000,000",제 52 기,2020.12.31 현재,"178,284,102,000,000",제 51 기,2019.12.31 현재,"172,288,326,000,000",19,KRW
22,20220308000798,11011,2021,00126380,005930,OFS,재무제표,BS,재무상태표,자본총계,제 53 기,2021.12.31 현재,"193,193,732,000,000",제 52 기,2020.12.31 현재,"183,316,724,000,000",제 51 기,2019.12.31 현재,"177,870,247,000,000",22,KRW
23,20220308000798,11011,2021,00126380,005930,OFS,재무제표,IS,손익계산서,매출액,제 53 기,2021.01.01 ~ 2021.12.31,"199,744,705,000,000",제 52 기,2020.01.01 ~ 2020.12.31,"166,311,191,000,000",제 51 기,2019.01.01 ~ 2019.12.31,"154,772,859,000,000",24,KRW
24,20220308000798,11011,2021,00126380,005930,OFS,재무제표,IS,손익계산서,영업이익,제 53 기,2021.01.01 ~ 2021.12.31,"31,993,162,000,000",제 52 기,2020.01.01 ~ 2020.12.31,"20,518,974,000,000",제 51 기,2019.01.01 ~ 2019.12.31,"14,115,067,000,000",26,KRW
25,20220308000798,11011,2021,00126380,005930,OFS,재무제표,IS,손익계산서,법인세차감전 순이익,제 53 기,2021.01.01 ~ 2021.12.31,"38,704,492,000,000",제 52 기,2020.01.01 ~ 2020.12.31,"20,451,923,000,000",제 51 기,2019.01.01 ~ 2019.12.31,"19,032,469,000,000",28,KRW
26,20220308000798,11011,2021,00126380,005930,OFS,재무제표,IS,손익계산서,당기순이익(손실),제 53 기,2021.01.01 ~ 2021.12.31,"30,970,954,000,000",제 52 기,2020.01.01 ~ 2020.12.31,"15,615,018,000,000",제 51 기,2019.01.01 ~ 2019.12.31,"15,353,323,000,000",30,KRW
27,20220308000798,11011,2021,00126380,005930,OFS,재무제표,IS,손익계산서,당기순이익(손실),제 53 기,2021.01.01 ~ 2021.12.31,"30,970,954,000,000",제 52 기,2020.01.01 ~ 2020.12.31,"15,615,018,000,000",제 51 기,2019.01.01 ~ 2019.12.31,"15,353,323,000,000",62,KRW

## 리턴하는 컬럼

한국 금융감독원 전자공시시스템(DART)의 Open API 데이터를 기반으로 하는 **DartFinanceReader** (주로 `dart-fss` 나 `OpenDartReader` 등에서 재무제표를 파싱할 때 사용)가 반환하는 DataFrame 컬럼들은 오픈DART의 **'재무제표 주요계정'** 및 **'단일회사 전체재무제표'** API 표준 항목들입니다.

---

### 1. 공시 및 기업 기본 정보

* **`rcept_no`** (접수번호): 해당 재무제표가 제출된 공시 보고서의 고유 번호 (14자리)입니다.
* **`reprt_code`** (보고서 코드): 공시 보고서의 종류를 나타내는 코드입니다.
    * `11013`: 1분기 보고서
    * `11012`: 반기 보고서
    * `11014`: 3분기 보고서
    * `11011`: 사업 보고서 (연말 결산)


* **`bsns_year`** (사업연도): 재무제표가 속한 기준 연도 (예: `2025`)입니다.
* **`corp_code`** (고유번호): DART에서 기업을 식별하기 위해 부여한 8자리 고유 고유번호입니다. (상장사 주식종목코드와 다름)
* **`stock_code`** (종목코드): 한국거래소(KRX) 상장 주식 종목 코드 (6자리)입니다. 비상장사인 경우 비어있을 수 있습니다.

---

### 2. 재무제표 구분 정보

* **`fs_div`** (재무제표구분): 연결재무제표와 별도(개별)재무제표를 구분하는 코드입니다.
    * `CFS`: 연결재무제표 (Consolidated Financial Statements)
    * `OFS`: 별도/개별재무제표 (Separate Financial Statements)


* **`fs_nm`** (재무제표명): 위 구분을 한글 명칭(`연결재무제표` 또는 `별도재무제표`)으로 표시한 것입니다.
* **`sj_div`** (재무제표종류 구분): 재무제표의 종류를 나타내는 코드입니다.
    * `BS`: 재무상태표 (Balance Sheet)
    * `IS`: 손익계산서 (Income Statement)
    * `CIS`: 포괄손익계산서 (Comprehensive Income Statement)
    * `CF`: 현금흐름표 (Cash Flow Statement)
    * `SCE`: 자본변동표 (Statement of Changes in Equity)


* **`sj_nm`** (재무제표종류명): 위 구분을 한글 명칭(`재무상태표`, `손익계산서` 등)으로 표시한 것입니다.
* **`account_nm`** (계정과목명): 재무제표에 표시된 계정의 이름 (예: `유동자산`, `매출액`, `당기순이익` 등)입니다.

---

### 3. 기간 및 금액 정보 (3개년도 비교)

DART 재무제표는 기본적으로 당기, 전기, 전전기 3개년 데이터를 함께 제공합니다.

| 구분 | 컬럼명 | 의미 | 설명 |
| --- | --- | --- | --- |
| **당기 (이번 분기/개념)** | **`thstrm_nm`**<br><br>**`thstrm_dt`**<br><br>**`thstrm_amount`** | 당기명<br><br>당기 일<br><br>당기 금액 | 예: 제 25 기<br><br>예: 2025.12.31 현재 (또는 기간)<br><br>해당 계정과목의 **현재 분기/연도 금액** |
| **전기 (직전 연도)** | **`frmtrm_nm`**<br><br>**`frmtrm_dt`**<br><br>**`frmtrm_amount`** | 전기명<br><br>전기 일자<br><br>전기 금액 | 예: 제 24 기<br><br>예: 2024.12.31 현재<br><br>해당 계정과목의 **직전 연도 금액** |
| **전전기 (2년 전 연도)** | **`bfefrmtrm_nm`**<br><br>**`bfefrmtrm_dt`**<br><br>**`bfefrmtrm_amount`** | 전전기명<br><br>전전기 일자<br><br>전전기 금액 | 예: 제 23 기<br><br>예: 2023.12.31 현재<br><br>해당 계정과목의 **2년 전 연도 금액** |

> 💡 **참고:** `thstrm` = This Term (당기), `frmtrm` = Former Term (전기), `bfefrmtrm` = Before Former Term (전전기)의 약어입니다.

---

### 4. 기타 정렬 및 통화 정보

* **`ord`** (정렬순서): 재무제표 상에서 해당 계정과목이 나오는 출력 순서입니다. 데이터를 원본 재무제표 순서대로 정렬할 때 유용합니다.
* **`currency`** (통화): 금액의 화폐 단위 (예: `KRW` 등)입니다.

---

### 팁

데이터 분석을 하실 때는 보통 `fs_div`로 연결/별도를 먼저 필터링하고, `sj_div`로 원하는 재무제표(예: `IS`로 손익계산서만 추출)를 선택한 뒤 `account_nm`과 `thstrm_amount`를 매핑하여 필요한 재무 지표를 계산하게 됩니다.

In [19]:
df = dart.finstate('삼성전자', 2021, reprt_code='11813')
df

,rcept_no,reprt_code,bsns_year,corp_code,stock_code,fs_div,fs_nm,sj_div,sj_nm,account_nm,thstrm_nm,thstrm_dt,thstrm_amount,frmtrm_nm,frmtrm_dt,frmtrm_amount,bfefrmtrm_nm,bfefrmtrm_dt,bfefrmtrm_amount,ord,currency
0,20220308000798,11813,2021,00126380,005930,CFS,연결재무제표,BS,재무상태표,유동자산,제 53 기,2021.12.31 현재,"218,163,185,000,000",제 52 기,2020.12.31 현재,"198,215,579,000,000",제 51 기,2019.12.31 현재,"181,385,260,000,000",1,KRW
1,20220308000798,11813,2021,00126380,005930,CFS,연결재무제표,BS,재무상태표,비유동자산,제 53 기,2021.12.31 현재,"208,457,973,000,000",제 52 기,2020.12.31 현재,"180,020,139,000,000",제 51 기,2019.12.31 현재,"171,179,237,000,000",3,KRW
2,20220308000798,11813,2021,00126380,005930,CFS,연결재무제표,BS,재무상태표,자산총계,제 53 기,2021.12.31 현재,"426,621,158,000,000",제 52 기,2020.12.31 현재,"378,235,718,000,000",제 51 기,2019.12.31 현재,"352,564,497,000,000",5,KRW
3,20220308000798,11813,2021,00126380,005930,CFS,연결재무제표,BS,재무상태표,유동부채,제 53 기,2021.12.31 현재,"88,117,133,000,000",제 52 기,2020.12.31 현재,"75,604,351,000,000",제 51 기,2019.12.31 현재,"63,782,764,000,000",7,KRW
4,20220308000798,11813,2021,00126380,005930,CFS,연결재무제표,BS,재무상태표,비유동부채,제 53 기,2021.12.31 현재,"33,604,094,000,000",제 52 기,2020.12.31 현재,"26,683,351,000,000",제 51 기,2019.12.31 현재,"25,901,312,000,000",9,KRW
5,20220308000798,11813,2021,00126380,005930,CFS,연결재무제표,BS,재무상태표,부채총계,제 53 기,2021.12.31 현재,"121,721,227,000,000",제 52 기,2020.12.31 현재,"102,287,702,000,000",제 51 기,2019.12.31 현재,"89,684,076,000,000",11,KRW
6,20220308000798,11813,2021,00126380,005930,CFS,연결재무제표,BS,재무상태표,자본금,제 53 기,2021.12.31 현재,"897,514,000,000",제 52 기,2020.12.31 현재,"897,514,000,000",제 51 기,2019.12.31 현재,"897,514,000,000",13,KRW
7,20220308000798,11813,2021,00126380,005930,CFS,연결재무제표,BS,재무상태표,이익잉여금,제 53 기,2021.12.31 현재,"293,064,763,000,000",제 52 기,2020.12.31 현재,"271,068,211,000,000",제 51 기,2019.12.31 현재,"254,582,894,000,000",17,KRW
8,20220308000798,11813,2021,00126380,005930,CFS,연결재무제표,BS,재무상태표,자본총계,제 53 기,2021.12.31 현재,"304,899,931,000,000",제 52 기,2020.12.31 현재,"275,948,016,000,000",제 51 기,2019.12.31 현재,"262,880,421,000,000",21,KRW
9,20220308000798,11813,2021,00126380,005930,CFS,연결재무제표,IS,손익계산서,매출액,제 53 기,2021.01.01 ~ 2021.12.31,"279,604,799,000,000",제 52 기,2020.01.01 ~ 2020.12.31,"236,806,988,000,000",제 51 기,2019.01.01 ~ 2019.12.31,"230,400,881,000,000",23,KRW
10,20220308000798,11813,2021,00126380,005930,CFS,연결재무제표,IS,손익계산서,영업이익,제 53 기,2021.01.01 ~ 2021.12.31,"51,633,856,000,000",제 52 기,2020.01.01 ~ 2020.12.31,"35,993,876,000,000",제 51 기,2019.01.01 ~ 2019.12.31,"27,768,509,000,000",25,KRW
11,20220308000798,11813,2021,00126380,005930,CFS,연결재무제표,IS,손익계산서,법인세차감전 순이익,제 53 기,2021.01.01 ~ 2021.12.31,"53,351,827,000,000",제 52 기,2020.01.01 ~ 2020.12.31,"36,345,117,000,000",제 51 기,2019.01.01 ~ 2019.12.31,"30,432,189,000,000",27,KRW
12,20220308000798,11813,2021,00126380,005930,CFS,연결재무제표,IS,손익계산서,당기순이익(손실),제 53 기,2021.01.01 ~ 2021.12.31,"39,907,450,000,000",제 52 기,2020.01.01 ~ 2020.12.31,"26,407,832,000,000",제 51 기,2019.01.01 ~ 2019.12.31,"21,738,865,000,000",29,KRW
13,20220308000798,11813,2021,00126380,005930,CFS,연결재무제표,IS,손익계산서,당기순이익(손실),제 53 기,2021.01.01 ~ 2021.12.31,"39,907,450,000,000",제 52 기,2020.01.01 ~ 2020.12.31,"26,407,832,000,000",제 51 기,2019.01.01 ~ 2019.12.31,"21,738,865,000,000",61,KRW
14,20220308000798,11813,2021,00126380,005930,OFS,재무제표,BS,재무상태표,유동자산,제 53 기,2021.12.31 현재,"73,553,416,000,000",제 52 기,2020.12.31 현재,"73,798,549,000,000",제 51 기,2019.12.31 현재,"72,659,080,000,000",2,KRW
15,20220308000798,11813,2021,00126380,005930,OFS,재무제표,BS,재무상태표,비유동자산,제 53 기,2021.12.31 현재,"177,558,768,000,000",제 52 기,2020.12.31 현재,"155,865,878,000,000",제 51 기,2019.12.31 현재,"143,521,840,000,000",4,KRW
16,20220308000798,11813,2021,00126380,005930,OFS,재무제표,BS,재무상태표,자산총계,제 53 기,2021.12.31 현재,"251,112,184,000,000",제 52 기,2020.12.31 현재,"229,664,427,000,000",제 51 기,2019.12.31 현재,"216,180,920,000,000",6,KRW
17,20220308000798,11813,2021,00126380,005930,OFS,재무제표,BS,재무상태표,유동부채,제 53 기,2021.12.31 현재,"53,067,303,000,000",제 52 기,2020.12.31 현재,"44,412,904,000,000",제 51 기,2019.12.31 현재,"36,237,164,000,000",8,KRW
18,20220308000798,11813,2021,00126380,005930,OFS,재무제표,BS,재무상태표,비유동부채,제 53 기,2021.12.31 현재,"4,851,149,000,000",제 52 기,2020.12.31 현재,"1,934,799,000,000",제 51 기,2019.12.31 현재,"2,073,509,000,000",10,KRW
19,20220308000798,11813,2021,00126380,005930,OFS,재무제표,BS,재무상태표,부채총계,제 53 기,2021.12.31 현재,"57,918,452,000,000",제 52 기,2020.12.31 현재,"46,347,703,000,000",제 51 기,2019.12.31 현재,"38,310,673,000,000",12,KRW
20,20220308000798,11813,2021,00126380,005930,OFS,재무제표,BS,재무상태표,자본금,제 53 기,2021.12.31 현재,"897,514,000,000",제 52 기,2020.12.31 현재,"897,514,000,000",제 51 기,2019.12.31 현재,"897,514,000,000",15,KRW
21,20220308000798,11813,2021,00126380,005930,OFS,재무제표,BS,재무상태표,이익잉여금,제 53 기,2021.12.31 현재,"188,774,335,000,000",제 52 기,2020.12.31 현재,"178,284,102,000,000",제 51 기,2019.12.31 현재,"172,288,326,000,000",19,KRW
22,20220308000798,11813,2021,00126380,005930,OFS,재무제표,BS,재무상태표,자본총계,제 53 기,2021.12.31 현재,"193,193,732,000,000",제 52 기,2020.12.31 현재,"183,316,724,000,000",제 51 기,2019.12.31 현재,"177,870,247,000,000",22,KRW
23,20220308000798,11813,2021,00126380,005930,OFS,재무제표,IS,손익계산서,매출액,제 53 기,2021.01.01 ~ 2021.12.31,"199,744,705,000,000",제 52 기,2020.01.01 ~ 2020.12.31,"166,311,191,000,000",제 51 기,2019.01.01 ~ 2019.12.31,"154,772,859,000,000",24,KRW
24,20220308000798,11813,2021,00126380,005930,OFS,재무제표,IS,손익계산서,영업이익,제 53 기,2021.01.01 ~ 2021.12.31,"31,993,162,000,000",제 52 기,2020.01.01 ~ 2020.12.31,"20,518,974,000,000",제 51 기,2019.01.01 ~ 2019.12.31,"14,115,067,000,000",26,KRW
25,20220308000798,11813,2021,00126380,005930,OFS,재무제표,IS,손익계산서,법인세차감전 순이익,제 53 기,2021.01.01 ~ 2021.12.31,"38,704,492,000,000",제 52 기,2020.01.01 ~ 2020.12.31,"20,451,923,000,000",제 51 기,2019.01.01 ~ 2019.12.31,"19,032,469,000,000",28,KRW
26,20220308000798,11813,2021,00126380,005930,OFS,재무제표,IS,손익계산서,당기순이익(손실),제 53 기,2021.01.01 ~ 2021.12.31,"30,970,954,000,000",제 52 기,2020.01.01 ~ 2020.12.31,"15,615,018,000,000",제 51 기,2019.01.01 ~ 2019.12.31,"15,353,323,000,000",30,KRW
27,20220308000798,11813,2021,00126380,005930,OFS,재무제표,IS,손익계산서,당기순이익(손실),제 53 기,2021.01.01 ~ 2021.12.31,"30,970,954,000,000",제 52 기,2020.01.01 ~ 2020.12.31,"15,615,018,000,000",제 51 기,2019.01.01 ~ 2019.12.31,"15,353,323,000,000",62,KRW

In [20]:
df['fs_div']   # 재무재표구분,

0     CFS
1     CFS
2     CFS
3     CFS
4     CFS
5     CFS
6     CFS
7     CFS
8     CFS
9     CFS
10    CFS
11    CFS
12    CFS
13    CFS
14    OFS
15    OFS
16    OFS
17    OFS
18    OFS
19    OFS
20    OFS
21    OFS
22    OFS
23    OFS
24    OFS
25    OFS
26    OFS
27    OFS
Name: fs_div, dtype: str

In [21]:
df['fs_div']  == 'CFS'

0      True
1      True
2      True
3      True
4      True
5      True
6      True
7      True
8      True
9      True
10     True
11     True
12     True
13     True
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
Name: fs_div, dtype: bool

In [22]:
df['sj_div']  # 재무재표종류

0     BS
1     BS
2     BS
3     BS
4     BS
5     BS
6     BS
7     BS
8     BS
9     IS
10    IS
11    IS
12    IS
13    IS
14    BS
15    BS
16    BS
17    BS
18    BS
19    BS
20    BS
21    BS
22    BS
23    IS
24    IS
25    IS
26    IS
27    IS
Name: sj_div, dtype: str

In [26]:
filtered_df = df[(df['fs_div'] == 'CFS') & (df['sj_div'] == 'BS')]
filtered_df

,rcept_no,reprt_code,bsns_year,corp_code,stock_code,fs_div,fs_nm,sj_div,sj_nm,account_nm,thstrm_nm,thstrm_dt,thstrm_amount,frmtrm_nm,frmtrm_dt,frmtrm_amount,bfefrmtrm_nm,bfefrmtrm_dt,bfefrmtrm_amount,ord,currency
0,20220308000798,11813,2021,00126380,005930,CFS,연결재무제표,BS,재무상태표,유동자산,제 53 기,2021.12.31 현재,"218,163,185,000,000",제 52 기,2020.12.31 현재,"198,215,579,000,000",제 51 기,2019.12.31 현재,"181,385,260,000,000",1,KRW
1,20220308000798,11813,2021,00126380,005930,CFS,연결재무제표,BS,재무상태표,비유동자산,제 53 기,2021.12.31 현재,"208,457,973,000,000",제 52 기,2020.12.31 현재,"180,020,139,000,000",제 51 기,2019.12.31 현재,"171,179,237,000,000",3,KRW
2,20220308000798,11813,2021,00126380,005930,CFS,연결재무제표,BS,재무상태표,자산총계,제 53 기,2021.12.31 현재,"426,621,158,000,000",제 52 기,2020.12.31 현재,"378,235,718,000,000",제 51 기,2019.12.31 현재,"352,564,497,000,000",5,KRW
3,20220308000798,11813,2021,00126380,005930,CFS,연결재무제표,BS,재무상태표,유동부채,제 53 기,2021.12.31 현재,"88,117,133,000,000",제 52 기,2020.12.31 현재,"75,604,351,000,000",제 51 기,2019.12.31 현재,"63,782,764,000,000",7,KRW
4,20220308000798,11813,2021,00126380,005930,CFS,연결재무제표,BS,재무상태표,비유동부채,제 53 기,2021.12.31 현재,"33,604,094,000,000",제 52 기,2020.12.31 현재,"26,683,351,000,000",제 51 기,2019.12.31 현재,"25,901,312,000,000",9,KRW
5,20220308000798,11813,2021,00126380,005930,CFS,연결재무제표,BS,재무상태표,부채총계,제 53 기,2021.12.31 현재,"121,721,227,000,000",제 52 기,2020.12.31 현재,"102,287,702,000,000",제 51 기,2019.12.31 현재,"89,684,076,000,000",11,KRW
6,20220308000798,11813,2021,00126380,005930,CFS,연결재무제표,BS,재무상태표,자본금,제 53 기,2021.12.31 현재,"897,514,000,000",제 52 기,2020.12.31 현재,"897,514,000,000",제 51 기,2019.12.31 현재,"897,514,000,000",13,KRW
7,20220308000798,11813,2021,00126380,005930,CFS,연결재무제표,BS,재무상태표,이익잉여금,제 53 기,2021.12.31 현재,"293,064,763,000,000",제 52 기,2020.12.31 현재,"271,068,211,000,000",제 51 기,2019.12.31 현재,"254,582,894,000,000",17,KRW
8,20220308000798,11813,2021,00126380,005930,CFS,연결재무제표,BS,재무상태표,자본총계,제 53 기,2021.12.31 현재,"304,899,931,000,000",제 52 기,2020.12.31 현재,"275,948,016,000,000",제 51 기,2019.12.31 현재,"262,880,421,000,000",21,KRW

In [27]:
filtered_df.empty

False

In [28]:
df[(df['fs_div'] == 'OFS') & (df['sj_div'] == 'BS')]

,rcept_no,reprt_code,bsns_year,corp_code,stock_code,fs_div,fs_nm,sj_div,sj_nm,account_nm,thstrm_nm,thstrm_dt,thstrm_amount,frmtrm_nm,frmtrm_dt,frmtrm_amount,bfefrmtrm_nm,bfefrmtrm_dt,bfefrmtrm_amount,ord,currency
14,20220308000798,11813,2021,00126380,005930,OFS,재무제표,BS,재무상태표,유동자산,제 53 기,2021.12.31 현재,"73,553,416,000,000",제 52 기,2020.12.31 현재,"73,798,549,000,000",제 51 기,2019.12.31 현재,"72,659,080,000,000",2,KRW
15,20220308000798,11813,2021,00126380,005930,OFS,재무제표,BS,재무상태표,비유동자산,제 53 기,2021.12.31 현재,"177,558,768,000,000",제 52 기,2020.12.31 현재,"155,865,878,000,000",제 51 기,2019.12.31 현재,"143,521,840,000,000",4,KRW
16,20220308000798,11813,2021,00126380,005930,OFS,재무제표,BS,재무상태표,자산총계,제 53 기,2021.12.31 현재,"251,112,184,000,000",제 52 기,2020.12.31 현재,"229,664,427,000,000",제 51 기,2019.12.31 현재,"216,180,920,000,000",6,KRW
17,20220308000798,11813,2021,00126380,005930,OFS,재무제표,BS,재무상태표,유동부채,제 53 기,2021.12.31 현재,"53,067,303,000,000",제 52 기,2020.12.31 현재,"44,412,904,000,000",제 51 기,2019.12.31 현재,"36,237,164,000,000",8,KRW
18,20220308000798,11813,2021,00126380,005930,OFS,재무제표,BS,재무상태표,비유동부채,제 53 기,2021.12.31 현재,"4,851,149,000,000",제 52 기,2020.12.31 현재,"1,934,799,000,000",제 51 기,2019.12.31 현재,"2,073,509,000,000",10,KRW
19,20220308000798,11813,2021,00126380,005930,OFS,재무제표,BS,재무상태표,부채총계,제 53 기,2021.12.31 현재,"57,918,452,000,000",제 52 기,2020.12.31 현재,"46,347,703,000,000",제 51 기,2019.12.31 현재,"38,310,673,000,000",12,KRW
20,20220308000798,11813,2021,00126380,005930,OFS,재무제표,BS,재무상태표,자본금,제 53 기,2021.12.31 현재,"897,514,000,000",제 52 기,2020.12.31 현재,"897,514,000,000",제 51 기,2019.12.31 현재,"897,514,000,000",15,KRW
21,20220308000798,11813,2021,00126380,005930,OFS,재무제표,BS,재무상태표,이익잉여금,제 53 기,2021.12.31 현재,"188,774,335,000,000",제 52 기,2020.12.31 현재,"178,284,102,000,000",제 51 기,2019.12.31 현재,"172,288,326,000,000",19,KRW
22,20220308000798,11813,2021,00126380,005930,OFS,재무제표,BS,재무상태표,자본총계,제 53 기,2021.12.31 현재,"193,193,732,000,000",제 52 기,2020.12.31 현재,"183,316,724,000,000",제 51 기,2019.12.31 현재,"177,870,247,000,000",22,KRW

In [31]:
filtered_df[['corp_code', 'bsns_year', 'reprt_code', 'account_nm', 'thstrm_amount']]

  corp_code bsns_year reprt_code account_nm        thstrm_amount
0  00126380      2021      11813       유동자산  218,163,185,000,000
1  00126380      2021      11813      비유동자산  208,457,973,000,000
2  00126380      2021      11813       자산총계  426,621,158,000,000
3  00126380      2021      11813       유동부채   88,117,133,000,000
4  00126380      2021      11813      비유동부채   33,604,094,000,000
5  00126380      2021      11813       부채총계  121,721,227,000,000
6  00126380      2021      11813        자본금      897,514,000,000
7  00126380      2021      11813      이익잉여금  293,064,763,000,000
8  00126380      2021      11813       자본총계  304,899,931,000,000

## 🔵함수 정의

In [34]:
def get_financial_statement(
    corp_code,
    date,
    report_code,
    sj_div,
):
    df = dart.finstate(corp_code, date, report_code)
    # 연결재무재표
    filtered_df = df[(df['fs_div'] == 'CFS') & (df['sj_div'] == sj_div)]
    if filtered_df.empty:
        # 혹시 없다면 OFS
        filtered_df = df[(df['fs_div'] == 'OFS') & (df['sj_div'] == sj_div)]

    filtered_df = filtered_df[['corp_code', 'bsns_year', 'reprt_code', 'account_nm', 'thstrm_amount']]
    return filtered_df

In [35]:
inputs = {
    'corp_code': '00126380',
    'date': '2025',
    'report_code': '11013',
    'sj_div': 'BS'
}

get_financial_statement(**inputs)

  corp_code bsns_year reprt_code account_nm        thstrm_amount
0  00126380      2025      11013       유동자산  222,685,717,000,000
1  00126380      2025      11013      비유동자산  293,691,031,000,000
2  00126380      2025      11013       자산총계  516,376,748,000,000
3  00126380      2025      11013       유동부채   90,279,712,000,000
4  00126380      2025      11013      비유동부채   19,482,767,000,000
5  00126380      2025      11013       부채총계  109,762,479,000,000
6  00126380      2025      11013        자본금      897,514,000,000
7  00126380      2025      11013      이익잉여금  373,062,171,000,000
8  00126380      2025      11013       자본총계  406,614,269,000,000

# report()

특정 기업의 사업보고서 내 특정 항목(예: 미등기임원보수, 증자, 배당 등)에 대한 정보를 조회하는 함수입니다.

```python
dart.report(기업명_또는_종목코드, 항목명, 연도) -> DataFrame
```

파라미터에는 기업명이나 종목코드(예: '삼성전자', '005930). 조회할 연도(예: 2021)와 조회할 사업보고서 내 항목 이름(미등기임원보수', '증자' 등)을 전달합니다.

In [36]:
# 삼성전자의 2021년 미등기임원보수 현황 조회
report = dart.report('005930', '미등기임원보수', 2021)
report

,rcept_no,corp_cls,corp_code,corp_name,se,fyer_salary_totamt,jan_salary_am,nmpr,rm,stlm_dt
0,20220308000798,Y,00126380,삼성전자,미등기임원,"717,856,000,000","790,000,000",933,-,2021-12-31

In [37]:
# 삼성전자의 2021년 증자 현황 조회
report = dart.report('005930', '증자', 2021)
report

,rcept_no,corp_cls,corp_code,corp_name,isu_dcrs_de,isu_dcrs_stle,isu_dcrs_stock_knd,isu_dcrs_qy,isu_dcrs_mstvdv_fval_amount,isu_dcrs_mstvdv_amount,stlm_dt
0,20220308000798,Y,00126380,삼성전자,-,-,-,-,-,-,2021-12-31

## 🔵함수 정의

In [38]:
REPORT_CODES = [
    '조건부자본증권미상환', '미등기임원보수', '회사채미상환', '단기사채미상환', '기업어음미상환',
    '채무증권발행', '사모자금사용', '공모자금사용', '임원전체보수승인', '임원전체보수유형',
    '주식총수', '회계감사', '감사용역', '회계감사용역계약', '사외이사', '신종자본증권미상환',
    '증자', '배당', '자기주식', '최대주주', '최대주주변동', '소액주주', '임원', '직원',
    '임원개인보수', '임원전체보수', '개인별보수', '타법인출자'
]

In [41]:
def get_specific_business_report(
    corp_code,
    report_code,
    date
):
    if report_code not in REPORT_CODES:
        return {"error": f"💥report_code must be on of : {RREPORT_CODES}"}

    result = dart.report(corp_code, report_code, date)

    if isinstance(result, pd.DataFrame) and result.empty:
        return {"message": "No data found for the given parameters."}

    return result

In [46]:
# 동작 확인
inputs = {
    "corp_code": "롯데렌탈",
    "report_code": "증자",
    "date": "2025",
}

get_specific_business_report(**inputs)

,rcept_no,corp_cls,corp_code,corp_name,isu_dcrs_de,isu_dcrs_stle,isu_dcrs_stock_knd,isu_dcrs_qy,isu_dcrs_mstvdv_fval_amount,isu_dcrs_mstvdv_amount,stlm_dt
0,20260316000884,Y,00545716,롯데렌탈,-,-,-,-,-,-,2025-12-31

# event()
특정 기업의 특정 이벤트(예: 영업정지, 증자 등)에 대한 주요사항보고서 정보를 조회하는 함수입니다.

```python
dart.event (기업명_또는 종목코드, 이벤트명, 연도) -> DataFrame
```

파라미터에는 기업명이나 종목코드(예: '삼성전자', '005930), 조회할 연도(예: 2021)와 이벤트명(예: '영업정지', '회생절차' 등)을 전달합니다.

- 조회가능한 주요사항 항목: 
  - ['부도발생', '영업정지', '회생절차', '해산사유', '유상증자', '무상증자', '유무상증자', '감자', '관리절차개시', '소송', '해외상장결정', '해외상장폐지결정', '해외상장', '해외상장폐지', '전환사채발행', '신주인수권부사채발행', '교환사채발행', '관리절차중단', '조건부자본증권발행', '자산양수도', '타법인증권양도', '유형자산양도', '유형자산양수', '타법인증권양수', '영업양도', '영업양수', '자기주식취득신탁계약해지', '자기주식취득신탁계약체결', '자기주식처분', '자기주식취득', '주식교환', '회사분할합병', '회사분할', '회사합병', '사채권양수', '사채권양도결정']

In [47]:
event = dart.event('052220', '영업정지', '2019')
event

,rcept_no,corp_cls,corp_code,corp_name,bsnsp_rm,bsnsp_amt,rsl,sl_vs,ls_atn,krx_stt_atn,bsnsp_cn,bsnsp_rs,ft_ctp,bsnsp_af,bsnspd,bddd,od_a_at_t,od_a_at_b,adt_a_atn
0,20190731000609,K,00370006,iMBC,콘텐츠사업부분 일부,"12,704,835,489","58,074,993,049",21.9,미해당,O,(주)문화방송 콘텐츠 국내 및 \n해외 유통 사업 일부,사업 계약 종료,광고 및 영상소재 서비스로의 사업 \n범위 확장,"영업정지로 총 매출액의 감소가 불가피하나, 신규 사업부문 확보를 통하여 영업이익으로...",2019년 07월 31일,2019년 07월 31일,2,-,참석

In [48]:
event = dart.event('017810', '전환사채발행')
event

,rcept_no,corp_cls,corp_code,corp_name,bddd,od_a_at_t,od_a_at_b,adt_a_atn,fdpp_fclt,fdpp_bsninh,fdpp_op,fdpp_dtrp,fdpp_ocsa,fdpp_etc,ftc_stt_atn,bd_tm,bd_knd,bd_fta,atcsc_rmislmt,ovis_fta,ovis_fta_crn,ovis_ster,ovis_isar,ovis_mktnm,bd_intr_ex,bd_intr_sf,bd_mtd,bdis_mthn,cv_rt,cv_prc,cvisstk_knd,cvisstk_cnt,cvisstk_tisstk_vs,cvrqpd_bgd,cvrqpd_edd,act_mktprcfl_cvprc_lwtrsprc,act_mktprcfl_cvprc_lwtrsprc_bs,rmislmt_lt70p,abmg,sbd,pymd,rpmcmp,grint,rs_sm_atn,ex_sm_r,ovis_ltdtl
0,20150804000320,Y,00155355,풀무원,2015년 08월 04일,6,0,참석,-,-,"30,000,000,000",-,-,-,미해당,63,무기명식 이권부 \n무보증 후순위 사모 전환사채,"30,000,000,000",-,-,-,-,-,-,2.5,2.5,2045년 08월 06일,사모,100,"236,585",주식회사 풀무원 기명식 보통주식,-,-,2016년 08월 06일,2045년 07월 06일,-,-,-,-,2015년 08월 06일,2015년 08월 06일,"NH투자증권, 신영증권",-,아니오,사모발행에 의한 1년간 행사금지 및 권면분할 금지,-
1,20190930000444,Y,00155355,풀무원,2019년 09월 09일,6,1,-,-,-,"70,000,000,000",-,-,-,미해당,66,무기명식 이권부 무보증 후순위 전환사채,"70,000,000,000",-,-,-,-,-,-,4.80,4.80,2049년 09월 30일,공모,100,"27,000",주식회사 풀무원 기명식 보통주식,"2,592,592",5.80,2019년 10월 30일,2049년 08월 30일,-,-,-,-,2019년 09월 25일,2019년 09월 30일,한국투자증권 주식회사,-,예,-,-
2,20230901000271,Y,00155355,풀무원,2023년 09월 01일,6,1,참석,-,-,-,"60,000,000,000",-,-,미해당,71,무기명식 이권부 무보증 후순위 사모 전환사채,"60,000,000,000","96,255,400,000",-,-,-,-,-,2.0,9.5,2053년 09월 05일,사모,100,"11,319",(주)풀무원 기명식 보통주식,"5,300,821",12.21,2026년 09월 06일,2053년 08월 05일,-,-,-,-,2023년 09월 05일,2023년 09월 05일,-,-,아니오,사모 발행으로 인한 증권신고서 제출 면제\n(발행일로부터 1년간 분할 및 병합 금지...,-
3,20230901000246,Y,00155355,풀무원,2023년 09월 01일,6,1,참석,-,-,-,"40,000,000,000",-,-,미해당,70,무기명식 이권부 무보증 후순위 사모 전환사채,"40,000,000,000","136,255,400,000",-,-,-,-,-,2.0,8.0,2053년 09월 05일,사모,100,"11,319",(주)풀무원 기명식 보통주식,"3,533,881",8.48,2024년 09월 06일,2053년 08월 05일,-,-,-,-,2023년 09월 05일,2023년 09월 05일,-,-,아니오,사모 발행으로 인한 증권신고서 제출 면제\n(발행일로부터 1년간 분할 및 병합 금지...,-

## 🔵 함수정의

In [49]:
EVENT_CODES = [
    '부도발생', '영업정지', '회생절차', '해산사유', '유상증자', '무상증자', '유무상증자', '감자',
    '관리절차개시', '소송', '해외상장결정', '해외상장폐지결정', '해외상장', '해외상장폐지',
    '전환사채발행', '신주인수권부사채발행', '교환사채발행', '관리절차중단', '조건부자본증권발행',
    '자산양수도', '타법인증권양도', '유형자산양도', '유형자산양수', '타법인증권양수', '영업양도',
    '영업양수', '자기주식취득신탁계약해지', '자기주식취득신탁계약체결', '자기주식처분', '자기주식취득',
    '주식교환', '회사분할합병', '회사분할', '회사합병', '사채권양수', '사채권양도결정'
]

In [50]:
def get_major_event_report(
    corp_code,
    event,
    date
):
    if event not in EVENT_CODES:
        return {"error": f"event must be one of: {EVENT_CODES}"}

    result = dart.event(corp_code, event, date)

    if isinstance(result, pd.DataFrame) and result.empty:
        return {'message': "No data found for the given parameters."}

    return result

In [51]:
inputs = {
    'corp_code': '052220',
    'event': '영업정지',
    'date': '2019'
}

get_major_event_report(**inputs)

,rcept_no,corp_cls,corp_code,corp_name,bsnsp_rm,bsnsp_amt,rsl,sl_vs,ls_atn,krx_stt_atn,bsnsp_cn,bsnsp_rs,ft_ctp,bsnsp_af,bsnspd,bddd,od_a_at_t,od_a_at_b,adt_a_atn
0,20190731000609,K,00370006,iMBC,콘텐츠사업부분 일부,"12,704,835,489","58,074,993,049",21.9,미해당,O,(주)문화방송 콘텐츠 국내 및 \n해외 유통 사업 일부,사업 계약 종료,광고 및 영상소재 서비스로의 사업 \n범위 확장,"영업정지로 총 매출액의 감소가 불가피하나, 신규 사업부문 확보를 통하여 영업이익으로...",2019년 07월 31일,2019년 07월 31일,2,-,참석